import React from "react"

const SvgFacility = props => (
    <svg
        id="Layer_1"
        x="0px"
        y="0px"
        viewBox="0 0 24 24"
        style={{
            enableBackground: "new 0 0 24 24",
        }}
        xmlSpace="preserve"
        height={props.height}
        width={props.height}
        {...props}
    >
        <g>
            <polygon
                fill="none"
                stroke={props.color}
                strokeWidth={2}
                strokeLinejoin="round"
                strokeMiterlimit={10}
                points="18,3 2,3 2,21 22,21 22,12 18,12"
            />
            <rect
                x={12}
                y={16}
                fill="none"
                stroke={props.color}
                strokeWidth={2}
                strokeLinejoin="round"
                strokeMiterlimit={10}
                width={6}
                height={5}
            />
            <line
                fill="none"
                stroke={props.color}
                strokeWidth={2}
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit={10}
                x1={6}
                y1={8}
                x2={8}
                y2={8}
            />
            <line
                fill="none"
                stroke={props.color}
                strokeWidth={2}
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit={10}
                x1={12}
                y1={8}
                x2={14}
                y2={8}
            />
            <line
                fill="none"
                stroke={props.color}
                strokeWidth={2}
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit={10}
                x1={12}
                y1={12}
                x2={14}
                y2={12}
            />
            <line
                fill="none"
                stroke={props.color}
                strokeWidth={2}
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit={10}
                x1={6}
                y1={12}
                x2={8}
                y2={12}
            />
            <line
                fill="none"
                stroke={props.color}
                strokeWidth={2}
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit={10}
                x1={6}
                y1={16}
                x2={8}
                y2={16}
            />
        </g>
        <g>
            <polygon
                fill="none"
                stroke={props.color}
                strokeWidth={2}
                strokeLinejoin="round"
                strokeMiterlimit={10}
                points="18,3 2,3 2,21 22,21 22,12 18,12  "
            />
            <rect
                x={12}
                y={16}
                fill="none"
                stroke={props.color}
                strokeWidth={2}
                strokeLinejoin="round"
                strokeMiterlimit={10}
                width={6}
                height={5}
            />
            <line
                fill="none"
                stroke={props.color}
                strokeWidth={2}
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit={10}
                x1={6}
                y1={8}
                x2={8}
                y2={8}
            />
            <line
                fill="none"
                stroke={props.color}
                strokeWidth={2}
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit={10}
                x1={12}
                y1={8}
                x2={14}
                y2={8}
            />
            <line
                fill="none"
                stroke={props.color}
                strokeWidth={2}
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit={10}
                x1={12}
                y1={12}
                x2={14}
                y2={12}
            />
            <line
                fill="none"
                stroke={props.color}
                strokeWidth={2}
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit={10}
                x1={6}
                y1={12}
                x2={8}
                y2={12}
            />
            <line
                fill="none"
                stroke={props.color}
                strokeWidth={2}
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit={10}
                x1={6}
                y1={16}
                x2={8}
                y2={16}
            />
        </g>
        <g>
            <polygon
                fill="none"
                stroke={props.color}
                strokeWidth={2}
                strokeLinejoin="round"
                strokeMiterlimit={10}
                points="18,3 2,3 2,21 22,21 22,12 18,12"
            />
            <rect
                x={12}
                y={16}
                fill="none"
                stroke={props.color}
                strokeWidth={2}
                strokeLinejoin="round"
                strokeMiterlimit={10}
                width={6}
                height={5}
            />
            <line
                fill="none"
                stroke={props.color}
                strokeWidth={2}
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit={10}
                x1={6}
                y1={8}
                x2={8}
                y2={8}
            />
            <line
                fill="none"
                stroke={props.color}
                strokeWidth={2}
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit={10}
                x1={12}
                y1={8}
                x2={14}
                y2={8}
            />
            <line
                fill="none"
                stroke={props.color}
                strokeWidth={2}
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit={10}
                x1={12}
                y1={12}
                x2={14}
                y2={12}
            />
            <line
                fill="none"
                stroke={props.color}
                strokeWidth={2}
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit={10}
                x1={6}
                y1={12}
                x2={8}
                y2={12}
            />
            <line
                fill="none"
                stroke={props.color}
                strokeWidth={2}
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeMiterlimit={10}
                x1={6}
                y1={16}
                x2={8}
                y2={16}
            />
        </g>
    </svg>
)

export default SvgFacility
